export const Jobs = [
  {
    id: 1,
    title: "SDE-1",
    logo: "https://img.naukimg.com/logo_images/groups/v1/1205138.gif",
    company: "Ola",
    desc: "Identify clients need and provide possible solution",
    type: "Remote",
    isApplied: false,
  },
  {
    id: 2,
    title: "Executive",
    logo: "https://img.naukimg.com/logo_images/groups/v1/1285014.gif",
    company: "Swiggy",
    desc: "Identify clients need and provide possible solution",
    type: "Office",
    isApplied: false,
  },
  {
    id: 3,
    title: "Backend-Engineer",
    logo: "https://img.naukimg.com/logo_images/groups/v1/4575629.gif",
    company: "Acko",
    desc: "Identify clients need and provide possible solution",
    type: "Remote",
    isApplied: false,
  },
  {
    id: 4,
    title: "Manager",
    logo: "https://img.naukimg.com/logo_images/groups/v1/555816.gif",
    company: "Uniphore",
    desc: "Provide solutions and manage",
    type: "Office",
    isApplied: false,
  },
  {
    id: 5,
    title: "Frontend developer",
    logo: "https://img.naukimg.com/logo_images/groups/v1/4622851.gif",
    company: "Razorpay",
    desc: "Develop the frontend of website",
    type: "Remote",
    isApplied: false,
  },
  {
    id: 6,
    title: "Java-Developer",
    logo: "https://img.naukimg.com/logo_images/groups/v1/1715696.gif",
    company: "Lenskart",
    desc: "backend  developer",
    type: "Remote",
    isApplied: false,
  },
  {
    id: 7,
    title: "System-Designer",
    logo: "https://img.naukimg.com/logo_images/groups/v1/2519816.gif",
    company: "Cars24",
    desc: "Design System layout",
    type: "Remote",
    isApplied: false,
  },
  {
    id: 8,
    title: "Sales Exec",
    logo: "https://img.naukimg.com/logo_images/groups/v1/3989906.gif",
    company: "Byjus",
    desc: "Regulate Sales",
    type: "Remote",
    isApplied: false,
  },
  {
    id: 9,
    title: "Support Officer",
    logo: "https://img.naukimg.com/logo_images/groups/v1/775108.gif",
    company: "LivSpace",
    desc: "Manage Client and Support",
    type: "Office",
    isApplied: false,
  },
  {
    id: 10,
    title: "System-Arch",
    logo: "https://img.naukimg.com/logo_images/groups/v1/1194340.gif",
    company: "NoBroker",
    desc: "Develop system architect",
    type: "office",
    isApplied: false,
  },
];
